# Generated by Django 5.2 on 2025-04-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('processeur', models.CharField(max_length=255)),
                ('memoire_ram', models.IntegerField()),
                ('stockage', models.CharField(max_length=255)),
                ('carte_graphique', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisations_recommandees', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ordinateurs/')),
            ],
        ),
    ]
